from app.db.db_webapp import get_postgres_connection

conn = get_postgres_connection()
cur = conn.cursor()

sql = """
CREATE OR REPLACE VIEW "vw_2g_kpi_realtime_daily" AS
 SELECT "2g_kpi_zte_daily".kpi_date AS date,
    "2g_kpi_zte_daily".nsa,
    "2g_kpi_zte_daily".city,
    "2g_kpi_zte_daily".me_name,
    "2g_kpi_zte_daily".siteid,
    "2g_kpi_zte_daily".total_payload,
    "2g_kpi_zte_daily".tch_traffic,
    "2g_kpi_zte_daily".sdcch_traffic,
    "2g_kpi_zte_daily"."Offic_full_traffic",
    "2g_kpi_zte_daily"."Offic_half_traffic",
    "2g_kpi_zte_daily".tch_avail_num,
    "2g_kpi_zte_daily".tch_avail_denum,
    "2g_kpi_zte_daily".cssr_num,
    "2g_kpi_zte_daily".cssr_denum,
    "2g_kpi_zte_daily"."2g_ccsr_num",
    "2g_kpi_zte_daily"."2g_ccsr_denum",
    "2g_kpi_zte_daily".hosr_num,
    "2g_kpi_zte_daily".hosr_denum,
    "2g_kpi_zte_daily".sdsr_num,
    "2g_kpi_zte_daily".sdsr_denum,
    "2g_kpi_zte_daily".tbf_dl_est_num,
    "2g_kpi_zte_daily".tbf_dl_est_denum,
    "2g_kpi_zte_daily".tbf_comp_num,
    "2g_kpi_zte_daily".tbf_comp_denum,
    "2g_kpi_zte_daily".tch_drop_num,
    "2g_kpi_zte_daily".tch_drop_denum,
    "2g_kpi_zte_daily".tch_block_num,
    "2g_kpi_zte_daily".tch_block_denum,
    "2g_kpi_zte_daily".sdcch_block_num,
    "2g_kpi_zte_daily".sdcch_block_denum,
    "2g_kpi_zte_daily".fastreturn_to_lte,
    "2g_kpi_zte_daily".icm_band35_num,
    "2g_kpi_zte_daily".icm_band35_denum,
    "2g_kpi_zte_daily".num_icm_interference_ono,
    "2g_kpi_zte_daily".denum_icm_interference_ono,
    "2g_kpi_zte_daily".mos_dl,
    "2g_kpi_zte_daily".mos_ul,
    "2g_kpi_zte_daily".sd_to_tch,
    "2g_kpi_zte_daily".cst,
    "2g_kpi_zte_daily".pdch_alocation_failure_rate_num,
    "2g_kpi_zte_daily".pdch_alocation_failure_rate_denum,
    "2g_kpi_zte_daily".num_ul_qual_0_5,
    "2g_kpi_zte_daily".denum_ul_qual,
    "2g_kpi_zte_daily".num_dl_qual_0_5,
    "2g_kpi_zte_daily".denum_dl_qual_0_5,
    "2g_kpi_zte_daily".gprs_dl_thp,
    "2g_kpi_zte_daily".edge_dl_thp,
    "2g_kpi_zte_daily".gprs_payload,
    "2g_kpi_zte_daily".edge_payload
   FROM "2g_kpi_zte_daily"
  WHERE "2g_kpi_zte_daily".kpi_date < CURRENT_DATE
UNION ALL
 SELECT "2g_kpi_zte".date,
    "2g_kpi_zte".nsa,
    "2g_kpi_zte".city,
    "2g_kpi_zte".me_name,
    "2g_kpi_zte".siteid,
    sum("2g_kpi_zte".total_payload) AS total_payload,
    sum("2g_kpi_zte".tch_traffic) AS tch_traffic,
    sum("2g_kpi_zte".sdcch_traffic) AS sdcch_traffic,
    sum("2g_kpi_zte"."Offic_full_traffic") AS "Offic_full_traffic",
    sum("2g_kpi_zte"."Offic_half_traffic") AS "Offic_half_traffic",
    sum("2g_kpi_zte".tch_avail_num) AS tch_avail_num,
    sum("2g_kpi_zte".tch_avail_denum) AS tch_avail_denum,
    sum("2g_kpi_zte".cssr_num) AS cssr_num,
    sum("2g_kpi_zte".cssr_denum) AS cssr_denum,
    sum("2g_kpi_zte"."2g_ccsr_num") AS "2g_ccsr_num",
    sum("2g_kpi_zte"."2g_ccsr_denum") AS "2g_ccsr_denum",
    sum("2g_kpi_zte".hosr_num) AS hosr_num,
    sum("2g_kpi_zte".hosr_denum) AS hosr_denum,
    sum("2g_kpi_zte".sdsr_num) AS sdsr_num,
    sum("2g_kpi_zte".sdsr_denum) AS sdsr_denum,
    sum("2g_kpi_zte".tbf_dl_est_num) AS tbf_dl_est_num,
    sum("2g_kpi_zte".tbf_dl_est_denum) AS tbf_dl_est_denum,
    sum("2g_kpi_zte".tbf_comp_num) AS tbf_comp_num,
    sum("2g_kpi_zte".tbf_comp_denum) AS tbf_comp_denum,
    sum("2g_kpi_zte".tch_drop_num) AS tch_drop_num,
    sum("2g_kpi_zte".tch_drop_denum) AS tch_drop_denum,
    sum("2g_kpi_zte".tch_block_num) AS tch_block_num,
    sum("2g_kpi_zte".tch_block_denum) AS tch_block_denum,
    sum("2g_kpi_zte".sdcch_block_num) AS sdcch_block_num,
    sum("2g_kpi_zte".sdcch_block_denum) AS sdcch_block_denum,
    sum("2g_kpi_zte".fastreturn_to_lte) AS fastreturn_to_lte,
    sum("2g_kpi_zte".icm_band35_num) AS icm_band35_num,
    sum("2g_kpi_zte".icm_band35_denum) AS icm_band35_denum,
    sum("2g_kpi_zte".num_icm_interference_ono) AS num_icm_interference_ono,
    sum("2g_kpi_zte".denum_icm_interference_ono) AS denum_icm_interference_ono,
    avg("2g_kpi_zte".mos_dl) AS mos_dl,
    avg("2g_kpi_zte".mos_ul) AS mos_ul,
    avg("2g_kpi_zte".sd_to_tch) AS sd_to_tch,
    avg("2g_kpi_zte".cst) AS cst,
    sum("2g_kpi_zte".pdch_alocation_failure_rate_num) AS pdch_alocation_failure_rate_num,
    sum("2g_kpi_zte".pdch_alocation_failure_rate_denum) AS pdch_alocation_failure_rate_denum,
    sum("2g_kpi_zte".num_ul_qual_0_5) AS num_ul_qual_0_5,
    sum("2g_kpi_zte".denum_ul_qual) AS denum_ul_qual,
    sum("2g_kpi_zte".num_dl_qual_0_5) AS num_dl_qual_0_5,
    sum("2g_kpi_zte".denum_dl_qual_0_5) AS denum_dl_qual_0_5,
    avg("2g_kpi_zte".gprs_dl_thp) AS gprs_dl_thp,
    avg("2g_kpi_zte".edge_dl_thp) AS edge_dl_thp,
    sum("2g_kpi_zte".gprs_payload) AS gprs_payload,
    sum("2g_kpi_zte".edge_payload) AS edge_payload
   FROM "2g_kpi_zte"
  WHERE "2g_kpi_zte".date > (( SELECT max("2g_kpi_zte_daily".kpi_date) AS max
           FROM "2g_kpi_zte_daily")) AND "2g_kpi_zte".nsa IS NOT NULL AND "2g_kpi_zte".city IS NOT NULL AND "2g_kpi_zte".me_name IS NOT NULL AND "2g_kpi_zte".siteid IS NOT NULL
  GROUP BY "2g_kpi_zte".date, "2g_kpi_zte".nsa, "2g_kpi_zte".city, "2g_kpi_zte".me_name, "2g_kpi_zte".siteid;
"""

try:
    cur.execute(sql)
    conn.commit()
    print("Successfully created vw_2g_kpi_realtime_daily!")

    sql2 = """
    CREATE OR REPLACE VIEW "vw_4g_kpi_realtime_daily" AS
  SELECT "4g_kpi_zte_daily".kpi_date AS date,
    "4g_kpi_zte_daily".nsa,
    "4g_kpi_zte_daily".city,
    "4g_kpi_zte_daily".subnetwork_name,
    "4g_kpi_zte_daily".siteid,
    "4g_kpi_zte_daily"."4g_payload_mb",
    "4g_kpi_zte_daily".dl_traffic_volume,
    "4g_kpi_zte_daily".ul_traffic_volume,
    "4g_kpi_zte_daily".dl_payload_ca_mbyte,
    "4g_kpi_zte_daily".ul_payload_ca_mbyte,
    "4g_kpi_zte_daily".cssr_num,
    "4g_kpi_zte_daily".cssr_denum,
    "4g_kpi_zte_daily".volte_traffic,
    "4g_kpi_zte_daily".max_rrc_conn_user,
    "4g_kpi_zte_daily".new_active_users,
    "4g_kpi_zte_daily".dl_prb_util_num,
    "4g_kpi_zte_daily".dl_prb_util_denum,
    "4g_kpi_zte_daily".ul_prb_util_num,
    "4g_kpi_zte_daily".ul_prb_util_denum,
    "4g_kpi_zte_daily".user_dl_thp_num,
    "4g_kpi_zte_daily".user_dl_thp_denum,
    "4g_kpi_zte_daily".user_ul_thp_num,
    "4g_kpi_zte_daily".user_ul_thp_denum,
    "4g_kpi_zte_daily".avail_num,
    "4g_kpi_zte_daily".avail_denum,
    "4g_kpi_zte_daily".erab_setup_num,
    "4g_kpi_zte_daily".erab_setup_denum,
    "4g_kpi_zte_daily".rrc_setup_num,
    "4g_kpi_zte_daily".rrc_setup_denum,
    "4g_kpi_zte_daily".s1_signaling_sr_num,
    "4g_kpi_zte_daily".s1_signaling_sr_denum,
    "4g_kpi_zte_daily".sdr_num,
    "4g_kpi_zte_daily".sdr_denum,
    "4g_kpi_zte_daily".ifho_num,
    "4g_kpi_zte_daily".ifho_denum,
    "4g_kpi_zte_daily".csfb_num,
    "4g_kpi_zte_daily".csfb_denum,
    "4g_kpi_zte_daily".se_v3_num,
    "4g_kpi_zte_daily".se_v3_denum,
    "4g_kpi_zte_daily".num_average_cqi,
    "4g_kpi_zte_daily".denum_average_cqi,
    "4g_kpi_zte_daily".inta_rat_ifho_num,
    "4g_kpi_zte_daily".inta_rat_ifho_denum,
    "4g_kpi_zte_daily".num_dl_avg_mcs,
    "4g_kpi_zte_daily".denum_dl_avg_mcs,
    "4g_kpi_zte_daily".num_ul_avg_mcs,
    "4g_kpi_zte_daily".denum_ul_avg_mcs,
    "4g_kpi_zte_daily".num_agg8,
    "4g_kpi_zte_daily".denum_agg8,
    "4g_kpi_zte_daily".srvcc_gsm_num,
    "4g_kpi_zte_daily".srvcc_gsm_denum,
    "4g_kpi_zte_daily".volte_call_drop_rate_mme_num,
    "4g_kpi_zte_daily".volte_call_drop_rate_mme_denum,
    "4g_kpi_zte_daily".erab_drop_num,
    "4g_kpi_zte_daily".erab_drop_denum,
    "4g_kpi_zte_daily".processing_delay_num,
    "4g_kpi_zte_daily".processing_delay_denum,
    "4g_kpi_zte_daily"."DL_CCE_Failure_Num",
    "4g_kpi_zte_daily"."DL_CCE_Failure_Denum",
    "4g_kpi_zte_daily"."UL_CCE_Failure_Num",
    "4g_kpi_zte_daily"."UL_CCE_Failure_Denum",
    "4g_kpi_zte_daily".num_rsrp_dbm,
    "4g_kpi_zte_daily".denum_rsrp_dbm,
    "4g_kpi_zte_daily"."Good_RSRP (>-105) Ratio Num",
    "4g_kpi_zte_daily"."Good_RSRP (>-105) Ratio Denum",
    "4g_kpi_zte_daily"."Number of Outgoing HO Preparation Attempts(based UL Service)",
    "4g_kpi_zte_daily"."Number of Outgoing HO Success(based UL Service)",
    "4g_kpi_zte_daily".average_cpu_utilization,
    "4g_kpi_zte_daily".peak_cpu_utilization,
    "4g_kpi_zte_daily".avg_rsrp_dbm,
    "4g_kpi_zte_daily"."Average of RSRQ Value of Serving Cell(period measurement)(dB)",
    "4g_kpi_zte_daily".avg_cell_rssi,
    "4g_kpi_zte_daily".average_ni_of_carrier,
    "4g_kpi_zte_daily".pucch_avg_ni_of_carrier,
    "4g_kpi_zte_daily".pusch_avg_ni_of_carrier,
    "4g_kpi_zte_daily".cell_uplink_init_bler,
    "4g_kpi_zte_daily".cell_downlink_init_bler,
    "4g_kpi_zte_daily".number_of_paging_records_received_by_the_enodeb,
    "4g_kpi_zte_daily".number_of_paging_records_discarded_at_the_enodeb
   FROM "4g_kpi_zte_daily"
  WHERE "4g_kpi_zte_daily".kpi_date < CURRENT_DATE
UNION ALL
 SELECT "4g_kpi_zte".date,
    "4g_kpi_zte".nsa,
    "4g_kpi_zte".city,
    "4g_kpi_zte".subnetwork_name,
    "4g_kpi_zte".siteid,
    sum("4g_kpi_zte"."4g_payload_mb") AS "4g_payload_mb",
    sum("4g_kpi_zte".dl_traffic_volume) AS dl_traffic_volume,
    sum("4g_kpi_zte".ul_traffic_volume) AS ul_traffic_volume,
    sum("4g_kpi_zte".dl_payload_ca_mbyte) AS dl_payload_ca_mbyte,
    sum("4g_kpi_zte".ul_payload_ca_mbyte) AS ul_payload_ca_mbyte,
    sum("4g_kpi_zte".cssr_num) AS cssr_num,
    sum("4g_kpi_zte".cssr_denum) AS cssr_denum,
    sum("4g_kpi_zte".volte_traffic) AS volte_traffic,
    sum("4g_kpi_zte".max_rrc_conn_user) AS max_rrc_conn_user,
    sum("4g_kpi_zte".new_active_users) AS new_active_users,
    sum("4g_kpi_zte".dl_prb_util_num) AS dl_prb_util_num,
    sum("4g_kpi_zte".dl_prb_util_denum) AS dl_prb_util_denum,
    sum("4g_kpi_zte".ul_prb_util_num) AS ul_prb_util_num,
    sum("4g_kpi_zte".ul_prb_util_denum) AS ul_prb_util_denum,
    sum("4g_kpi_zte".user_dl_thp_num) AS user_dl_thp_num,
    sum("4g_kpi_zte".user_dl_thp_denum) AS user_dl_thp_denum,
    sum("4g_kpi_zte".user_ul_thp_num) AS user_ul_thp_num,
    sum("4g_kpi_zte".user_ul_thp_denum) AS user_ul_thp_denum,
    sum("4g_kpi_zte".avail_num) AS avail_num,
    sum("4g_kpi_zte".avail_denum) AS avail_denum,
    sum("4g_kpi_zte".erab_setup_num) AS erab_setup_num,
    sum("4g_kpi_zte".erab_setup_denum) AS erab_setup_denum,
    sum("4g_kpi_zte".rrc_setup_num) AS rrc_setup_num,
    sum("4g_kpi_zte".rrc_setup_denum) AS rrc_setup_denum,
    sum("4g_kpi_zte".s1_signaling_sr_num) AS s1_signaling_sr_num,
    sum("4g_kpi_zte".s1_signaling_sr_denum) AS s1_signaling_sr_denum,
    sum("4g_kpi_zte".sdr_num) AS sdr_num,
    sum("4g_kpi_zte".sdr_denum) AS sdr_denum,
    sum("4g_kpi_zte".ifho_num) AS ifho_num,
    sum("4g_kpi_zte".ifho_denum) AS ifho_denum,
    sum("4g_kpi_zte".csfb_num) AS csfb_num,
    sum("4g_kpi_zte".csfb_denum) AS csfb_denum,
    sum("4g_kpi_zte".se_v3_num) AS se_v3_num,
    sum("4g_kpi_zte".se_v3_denum) AS se_v3_denum,
    sum("4g_kpi_zte".num_average_cqi) AS num_average_cqi,
    sum("4g_kpi_zte".denum_average_cqi) AS denum_average_cqi,
    sum("4g_kpi_zte".inta_rat_ifho_num) AS inta_rat_ifho_num,
    sum("4g_kpi_zte".inta_rat_ifho_denum) AS inta_rat_ifho_denum,
    sum("4g_kpi_zte".num_dl_avg_mcs) AS num_dl_avg_mcs,
    sum("4g_kpi_zte".denum_dl_avg_mcs) AS denum_dl_avg_mcs,
    sum("4g_kpi_zte".num_ul_avg_mcs) AS num_ul_avg_mcs,
    sum("4g_kpi_zte".denum_ul_avg_mcs) AS denum_ul_avg_mcs,
    sum("4g_kpi_zte".num_agg8) AS num_agg8,
    sum("4g_kpi_zte".denum_agg8) AS denum_agg8,
    sum("4g_kpi_zte".srvcc_gsm_num) AS srvcc_gsm_num,
    sum("4g_kpi_zte".srvcc_gsm_denum) AS srvcc_gsm_denum,
    sum("4g_kpi_zte".volte_call_drop_rate_mme_num) AS volte_call_drop_rate_mme_num,
    sum("4g_kpi_zte".volte_call_drop_rate_mme_denum) AS volte_call_drop_rate_mme_denum,
    sum("4g_kpi_zte".erab_drop_num) AS erab_drop_num,
    sum("4g_kpi_zte".erab_drop_denum) AS erab_drop_denum,
    sum("4g_kpi_zte".processing_delay_num) AS processing_delay_num,
    sum("4g_kpi_zte".processing_delay_denum) AS processing_delay_denum,
    sum("4g_kpi_zte"."DL_CCE_Failure_Num") AS "DL_CCE_Failure_Num",
    sum("4g_kpi_zte"."DL_CCE_Failure_Denum") AS "DL_CCE_Failure_Denum",
    sum("4g_kpi_zte"."UL_CCE_Failure_Num") AS "UL_CCE_Failure_Num",
    sum("4g_kpi_zte"."UL_CCE_Failure_Denum") AS "UL_CCE_Failure_Denum",
    sum("4g_kpi_zte".num_rsrp_dbm) AS num_rsrp_dbm,
    sum("4g_kpi_zte".denum_rsrp_dbm) AS denum_rsrp_dbm,
    sum("4g_kpi_zte"."Good_RSRP (>-105) Ratio Num") AS "Good_RSRP (>-105) Ratio Num",
    sum("4g_kpi_zte"."Good_RSRP (>-105) Ratio Denum") AS "Good_RSRP (>-105) Ratio Denum",
    sum("4g_kpi_zte"."Number of Outgoing HO Preparation Attempts(based UL Service)") AS "Number of Outgoing HO Preparation Attempts(based UL Service)",
    sum("4g_kpi_zte"."Number of Outgoing HO Success(based UL Service)") AS "Number of Outgoing HO Success(based UL Service)",
    avg("4g_kpi_zte".average_cpu_utilization) AS average_cpu_utilization,
    avg("4g_kpi_zte".peak_cpu_utilization) AS peak_cpu_utilization,
    avg("4g_kpi_zte".avg_rsrp_dbm) AS avg_rsrp_dbm,
    avg("4g_kpi_zte"."Average of RSRQ Value of Serving Cell(period measurement)(dB)") AS "Average of RSRQ Value of Serving Cell(period measurement)(dB)",
    avg("4g_kpi_zte".avg_cell_rssi) AS avg_cell_rssi,
    avg("4g_kpi_zte".average_ni_of_carrier) AS average_ni_of_carrier,
    avg("4g_kpi_zte".pucch_avg_ni_of_carrier) AS pucch_avg_ni_of_carrier,
    avg("4g_kpi_zte".pusch_avg_ni_of_carrier) AS pusch_avg_ni_of_carrier,
    avg("4g_kpi_zte".cell_uplink_init_bler) AS cell_uplink_init_bler,
    avg("4g_kpi_zte".cell_downlink_init_bler) AS cell_downlink_init_bler,
    sum("4g_kpi_zte".number_of_paging_records_received_by_the_enodeb) AS number_of_paging_records_received_by_the_enodeb,
    sum("4g_kpi_zte".number_of_paging_records_discarded_at_the_enodeb) AS number_of_paging_records_discarded_at_the_enodeb
   FROM "4g_kpi_zte"
  WHERE "4g_kpi_zte".date > (( SELECT max("4g_kpi_zte_daily".kpi_date) AS max
           FROM "4g_kpi_zte_daily")) AND "4g_kpi_zte".nsa IS NOT NULL AND "4g_kpi_zte".city IS NOT NULL AND "4g_kpi_zte".subnetwork_name IS NOT NULL AND "4g_kpi_zte".siteid IS NOT NULL
  GROUP BY "4g_kpi_zte".date, "4g_kpi_zte".nsa, "4g_kpi_zte".city, "4g_kpi_zte".subnetwork_name, "4g_kpi_zte".siteid;
    """
    cur.execute(sql2)
    conn.commit()
    print("Successfully created vw_4g_kpi_realtime_daily!")
except Exception as e:
    import traceback
    traceback.print_exc()
